import streamlit as st
import json
from pathlib import Path


st.set_page_config(page_title="ML Model Referee", layout="wide")
st.title("🧑‍⚖️ ML Model Referee")
st.caption("A referee-style tool that compares ML models and explains trade-offs")

st.divider()

KIRO_OUTPUTS = Path(".kiro/outputs")

def load_json(filename):
    with open(KIRO_OUTPUTS / filename, "r") as f:
        return json.load(f)

def load_md(filename):
    with open(KIRO_OUTPUTS / filename, "r") as f:
        return f.read()

kiro_data = load_json("model_comparison.json")
summary = kiro_data["summary_matrix"]
tradeoffs = kiro_data["trade_offs"]


st.subheader("🔧 Define Your Constraints")

col1, col2, col3 = st.columns(3)

with col1:
    dataset_size = st.selectbox(
        "Dataset Size",
        ["Small (<10k rows)", "Medium (10k–1M rows)", "Large (>1M rows)"]
    )

with col2:
    interpretability = st.selectbox(
        "Interpretability Required?",
        ["High", "Medium", "Low"]
    )

with col3:
    accuracy_priority = st.selectbox(
        "Accuracy Priority",
        ["Low", "Medium", "High"]
    )

st.divider()


st.subheader("📊 Model Comparison (Generated by Kiro)")

st.table({
    "Criteria": summary["criteria"],
    "Logistic Regression": summary["logistic_regression"],
    "Random Forest": summary["random_forest"],
    "XGBoost": summary["xgboost"]
})


st.subheader("⚖️ Key Trade-offs (Kiro Analysis)")

for key, value in tradeoffs.items():
    st.info(f"**{key.replace('_', ' ').title()}**: {value}")


st.subheader("🧠 Referee Guidance (Conditional)")

if interpretability == "High":
    st.info(
        "If interpretability is the top priority, **Logistic Regression** fits best, "
        "but accuracy may be limited on complex non-linear data."
    )

if accuracy_priority == "High":
    st.info(
        "If accuracy is the top priority, **XGBoost** offers strong performance, "
        "but requires more tuning and reduces explainability."
    )

if dataset_size.startswith("Large"):
    st.info(
        "For very large datasets, **Logistic Regression** scales efficiently, "
        "while ensemble methods may require more resources."
    )

st.warning(
    "There is no universally best model. The right choice depends on which constraints matter most."
)


try:
    st.subheader("📌 Additional Guidance (From Kiro)")
    guidance = load_md("conditional_guidance.md")
    st.markdown(guidance)
except FileNotFoundError:
    pass

st.divider()
st.caption("Powered by Kiro • Built as a decision-support referee, not a recommendation engine")
